#!/usr/bin/perl
#
# STDOUT module
# by nitr0us (nitrousenador@gmail.com)
# http://chatsubo-labs.blogspot.com
#
#
# This module simply sends the traversal patterns
# generated by the Traversal Engine to STDOUT.
#
# Pretty easy but VERY USEFUL ! if you use it along with
# your ninja skills in scripting or other tools.
#
# Read the EXAMPLES.txt to see some examples on how to
# use it

package DotDotPwn::STDOUT;
use Exporter 'import';
@EXPORT = qw(toSTDOUT);

sub toSTDOUT{
	foreach(@main::traversals){
		print $_ . "\n";
	}
}
